spring.application.name=autenticacao

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false


jwt.secret=${JWT_SECRET}
jwt.access-token.expiracao-ms=1800000

brevo.api-key=${BREVO_API_KEY:}
brevo.remetente.email=${BREVO_REMETENTE_EMAIL}
brevo.remetente.nome=Sistema Bancario - Autenticacao

